version: '3'
services:
  bluetooth_player:
    container_name: bluetooth_player
    image: localhost:5001/bluealsa
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:rw
    tmpfs:
      - /run
    restart: unless-stopped
    # network_mode: "host"
    #devices:
    #  - /dev/ttyAMA0:/dev/ttyAMA0
    stdin_open: true
    tty: true
