version: '3'
services:
  bluetooth_player:
    container_name: bluetooth_player
    image: bluealsa
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    stdin_open: true
    tty: true
